// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web3MusicStore.API.Models;

#nullable disable

namespace Web3MusicStore.API.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20221017015337_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Web3MusicStore.API.Models.Album", b =>
                {
                    b.Property<string>("album_id")
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<string>("album_type")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("artists")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("billboard")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("image_url")
                        .HasColumnType("NVARCHAR(600)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int?>("popularity")
                        .HasColumnType("int");

                    b.Property<int>("total_tracks")
                        .HasColumnType("int");

                    b.HasKey("album_id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Web3MusicStore.API.Models.Artist", b =>
                {
                    b.Property<string>("artist_id")
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<string>("artist_type")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int?>("followers")
                        .HasColumnType("int");

                    b.Property<string>("genres")
                        .HasColumnType("longtext");

                    b.Property<string>("image_url")
                        .HasColumnType("NVARCHAR(600)");

                    b.Property<string>("main_genre")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int?>("popularity")
                        .HasColumnType("int");

                    b.HasKey("artist_id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Web3MusicStore.API.Models.Release", b =>
                {
                    b.Property<string>("album_id")
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<string>("artist_id")
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<string>("release_date")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("release_date_precision")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.HasKey("album_id", "artist_id");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Web3MusicStore.API.Models.Song", b =>
                {
                    b.Property<string>("song_id")
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<bool?>("Explicit")
                        .HasColumnType("BOOLEAN(1)")
                        .HasColumnName("explicit");

                    b.Property<string>("artists")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("billboard")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int?>("popularity")
                        .HasColumnType("int");

                    b.Property<string>("release_date_precision")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("song_name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("song_type")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("song_id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Web3MusicStore.API.Models.Track", b =>
                {
                    b.Property<string>("song_id")
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<string>("album_id")
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<string>("release_date")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("release_date_precision")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<int>("track_number")
                        .HasColumnType("int");

                    b.HasKey("song_id", "album_id");

                    b.ToTable("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
